import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import { Lexend } from 'next/font/google'

import './globals.css'

const mulish = Mulish({ 
  subsets: ['latin'],
  variable: '--font-mulish'
})
const lexend = Lexend({ 
  subsets: ['latin'],
  variable: '--font-lexend'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${mulish.variable} ${lexend.variable}`}>

      <body>
        {children}
      </body>

    </html>
  )
}
